### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered - during inference stage

### ISSUE THREAD

**Issue by bwang482** [dreamquark-ai/tabnet#386]
**Describe the bug**
I am running into `RuntimeError: CUDA error: device-side assert triggered` when making predictions on my test data.

**What is the current behavior?**
After 10 epochs of training, albeit both `train_auc` and `valid_auc` are awful compared to other models. I have decided to apply a trained classifier to my test data and that's when the CUDA error occurred. 
**If the current behavior is a bug, please provide the steps to reproduce.**
I am afraid I am using private data and cannot share it. My features are all categorical, which are derived either from binning or one-hot encoding (so many are counts). 

Below is what I did following the example jupyter notebooks to define categorical features and dims:
```
categorical_columns = feature_names
categorical_dims =  {}
for i in range(X_train.shape[1]):
    categorical_dims[feature_names[i]] = len(np.unique(X_train.getcol(i).toarray()))

cat_idxs = [i for i, f in enumerate(feature_names) if f in categorical_columns]
cat_dims = [categorical_dims[f] for i, f in enumerate(feature_names) if f in categorical_columns]
```
I am using a GPU (`Device used : cuda`), and the hyperparameter choices are simply copied from an example here:
```
clf = TabNetClassifier(
    n_d=64, n_a=64, n_steps=5,
    gamma=1.5, n_independent=2, n_shared=2,
    cat_idxs=cat_idxs,
    cat_dims=cat_dims,
    cat_emb_dim=1,
    lambda_sparse=1e-4, momentum=0.3, clip_value=2.,
    optimizer_fn=torch.optim.Adam,
    optimizer_params=dict(lr=2e-2),
    scheduler_params = {"gamma": 0.95,
                     "step_size": 20},
    scheduler_fn=torch.optim.lr_scheduler.StepLR, 
    epsilon=1e-15,
    device_name="auto"
)
```
Training performance is bad:
```
clf.fit(
    X_train=x_train, y_train=y_train,
    eval_set=[(x_train, y_train), (x_val, y_val)],
    eval_name=['train', 'valid'],
    eval_metric=['auc'],
    max_epochs=100 , patience=10,
    batch_size=1024, virtual_batch_size=128,
)
​
epoch 0  | loss: 0.02333 | train_auc: 0.52572 | valid_auc: 0.55781 |  0:21:36s
epoch 1  | loss: 0.01288 | train_auc: 0.49525 | valid_auc: 0.45546 |  0:43:08s
epoch 2  | loss: 0.01246 | train_auc: 0.48608 | valid_auc: 0.54022 |  1:04:40s
epoch 3  | loss: 0.01218 | train_auc: 0.49686 | valid_auc: 0.51621 |  1:25:17s
epoch 4  | loss: 0.01209 | train_auc: 0.48224 | valid_auc: 0.50605 |  1:46:04s
epoch 5  | loss: 0.01225 | train_auc: 0.50008 | valid_auc: 0.51382 |  2:07:08s
epoch 6  | loss: 0.01189 | train_auc: 0.50827 | valid_auc: 0.51544 |  2:28:04s
epoch 7  | loss: 0.01185 | train_auc: 0.5211  | valid_auc: 0.47366 |  2:48:44s
epoch 8  | loss: 0.01197 | train_auc: 0.49405 | valid_auc: 0.50044 |  3:09:45s
epoch 9  | loss: 0.01163 | train_auc: 0.50984 | valid_auc: 0.46645 |  3:30:41s
epoch 10 | loss: 0.01173 | train_auc: 0.47489 | valid_auc: 0.48854 |  3:51:27s

Early stopping occurred at epoch 10 with best_epoch = 0 and best_valid_auc = 0.55781
Best weights from best epoch are automatically used!
```
And finally this where the error occurred, during inference:
```
preds = clf.predict_proba(X_test.toarray()[:1000])
test_auc = roc_auc_score(y_score=preds[:,1], y_true=np.array(y_test))
​

preds_valid = clf.predict_proba(x_val)
valid_auc = roc_auc_score(y_score=preds_valid[:,1], y_true=y_val)
​
print(f"BEST VALID SCORE: {clf.best_cost}")
print(f"FINAL TEST SCORE: {test_auc}")
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_16220/1787765779.py in <module>
----> 1 preds = clf.predict_proba(X_test.toarray()[:1000])
      2 test_auc = roc_auc_score(y_score=preds[:,1], y_true=np.array(y_test))
      3 
      4 
      5 preds_valid = clf.predict_proba(x_val)

D:\bo\envs\bd\lib\site-packages\pytorch_tabnet\tab_model.py in predict_proba(self, X)
     98         results = []
     99         for batch_nb, data in enumerate(dataloader):
--> 100             data = data.to(self.device).float()
    101 
    102             output, M_loss = self.network(data)

RuntimeError: CUDA error: device-side assert triggered
```

**Expected behavior**
The model makes predictions and AUC for the test data is calculated. 

**Screenshots**

**Other relevant information:**
poetry version:  not using poetry
python version: **Python 3.7.11**
Operating System: **Windows 10**
Additional tools: **I am running the experiment on a jupyter notebook**

**Additional context**

I have installed `tabnet` using pip, and didn't `poetry install` or `make notebook`.

**Comment by bwang482** [comment]
I have run it again on terminal instead of jupyter notebook and got the same error though with more info:

```
Device used : cuda
epoch 0  | loss: 0.02333 | train_auc: 0.52572 | valid_auc: 0.55781 |  0:21:03s
epoch 1  | loss: 0.01288 | train_auc: 0.49525 | valid_auc: 0.45546 |  0:41:56s
epoch 2  | loss: 0.01246 | train_auc: 0.48608 | valid_auc: 0.54022 |  1:02:49s

Early stopping occurred at epoch 2 with best_epoch = 0 and best_valid_auc = 0.55781
Best weights from best epoch are automatically used!
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/Indexing.cu:662: block: [6,0,0], thread: [32,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
Traceback (most recent call last):
  File ".\main.py", line 60, in <module>
    main()
  File ".\main.py", line 54, in main
    tabnet_model(X_train, y_train, X_test, y_test, feature_names, 'TabNet', args)
  File "D:\bo\EOBD_prediction\exps\tabnet.py", line 22, in tabnet_model
    yte_pred = clf.predict_proba(Xte.toarray())
  File "D:\bo\envs\bd\lib\site-packages\pytorch_tabnet\tab_model.py", line 102, in predict_proba
    output, M_loss = self.network(data)
  File "D:\bo\envs\bd\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\bo\envs\bd\lib\site-packages\pytorch_tabnet\tab_network.py", line 582, in forward
    x = self.embedder(x)
  File "D:\bo\envs\bd\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\bo\envs\bd\lib\site-packages\pytorch_tabnet\tab_network.py", line 849, in forward
    self.embeddings[cat_feat_counter](x[:, feat_init_idx].long())
  File "D:\bo\envs\bd\lib\site-packages\torch\nn\modules\module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\bo\envs\bd\lib\site-packages\torch\nn\modules\sparse.py", line 158, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "D:\bo\envs\bd\lib\site-packages\torch\nn\functional.py", line 1916, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: CUDA error: device-side assert triggered
```

**Comment by Optimox** [comment]
Hello @bwang482,

Thanks for you encouraging comments.

> After 10 epochs of training, albeit both train_auc and valid_auc are awful compared to other models. I have decided to apply a trained classifier to my test data and that's when the CUDA error occurred.

Sorry to hear that your results are awful, but without further information on your classified dataset I can't help you much. The only thing I can tell you for sure is that something is wrong with your TabNet pipeline: if other model find information in your data then TabNet will too, it's not possible to get stuck with AUC=0.48 with a correct pipeline and dataset.

About your error, is it possible that you have unknown values in one of your categorical column in the test set ? The model will crash if given unknown indexes.

**Comment by bwang482** [comment]
Thanks @Optimox !

I will modify my features and adjust the hyperparameters, so I am not overly concerned about the training results rn.

My features are mostly counting features by `countvectorizer`, I have checked my test data doesn't have any `nan` or `inf` values. Or do you mean unknown values as values that are not in `categorical_dims`? If so, then yes, `categorical_dims` is computed from my training data.

**Comment by Optimox** [comment]
If you are using embeddings, then you can't have have new indexes during inference.

if column 1 uses embeddings on 4 values ([0, 1, 2, 3]) during training, then during inference if one of the rows of column 1 in test set is different from [0, 1, 2, 3] then you'll get an error.

What happens if you try to predict on your training set ? If it works you probably have new categories in your testing data.

**Comment by bwang482** [comment]
Thanks @Optimox !

But the point of inference is to predict what happens in unseen data where unseen feature values are highly likely to occur, no? i.e. it's not possible to cover all possible feature values in training data. For example in my case, my features are counts so pretty sure in the test data there are unseen counts that are not in the training data. 

Wait, or are these counting features generated by `countvectorizer` not considered categorical features. Sorry.

**Comment by bwang482** [comment]
Many thanks @Optimox !

I have made a huge mistake by treating my counting features as categorical features. Counts are ordinal by nature. Simply yet detrimental mistake. 

I have rerun my code after making sure correct categorical feature indices are fed to the model, and the cuda error disappeared. Thanks again.

**Comment by bwang482** [comment]
No, still far worse than tree models. I am thinking what's the best way of representing these counting features. I have lots of them. Maybe transform them into categorical features by setting non-zero counts to 1. Am I right the numerical features are not mapped to trainable embeddings? Do you have any insights on the use of counting features? e.g. number of times a customer has bought certain items, or number of times someone has listened to certain songs etc. 

Thanks!

**Comment by Optimox** [comment]
Numerical features won't use any embedding scheme. Counts should be fine, I don't know what is going wrong then.
