### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by omkarmutreja12** [dreamquark-ai/tabnet#418]
**Describe the bug**
I get this CUDA error when trying to fit the trained Tabnet classifier on unseen inference dataset (with GPU).

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Expected behavior**

**Screenshots**

**Other relevant information:**
poetry version:  
python version: 
Operating System: 
Additional tools:

**Additional context**

![image](https://user-images.githubusercontent.com/100974560/178298629-2814e69b-ceb4-4510-b220-89ae0f95eace.png)

**Comment by Optimox** [comment]
can you try to make the inference on CPU and see if you still have an error ?

**Comment by omkarmutreja12** [comment]
@Optimox  - Tried on CPU, the model is predicting on inference data, for GPU, it raises the CUDA error: device-side assert triggered.

**Comment by Optimox** [comment]
Have you trained the model with the same machine on GPU?

What does your inference computer says when trying torch.cuda.is_available?

**Comment by Optimox** [comment]
@omkarmutreja12 do you have any new information about your issue ?

**Comment by omkarmutreja12** [comment]
@Optimox  - Hey apologies for the delayed response, the problem is solved, there was an issue with the categorical column encoding, had one extra level which was not present in train, fixed it and it's running fine now, thanks!
